export const FILTER = 'FILTER';

//course List
export const GET_COURSE_LIST_URL = 'GET_COURSE_LIST_URL';
export const COURSE_LIST = 'COURSE_LIST';
export const COURSE_LIST_SUCCESS = 'COURSE_LIST_SUCCESS';
export const COURSE_LIST_FAILURE = 'COURSE_LIST_FAILURE';
export const LOGGED_IN = "LOGGED_IN";
export const FILTER_OPTIONS = "FILTER_OPTIONS";